README.md
=> Add git to dependencies.

src/aur_download.rs, src/main.rs, src/pacman.rs, src/srcinfo.rs, src/tar_check.rs, src/util.rs, src/wrapped.rs
Hi!
I want to implement a search with results in the terminal. For that I first fixed all clippy lints as seen in the first commit of this PR. The most "fixes" are just [expect_fun_call](https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call) things. So you basically save one `format` call that is unnecessary the most time.
Let me know how you think about that changes!
=> Clippy fixes

src/wrapped.rs
See [this](https://github.com/vn971/rua/issues/9) issue.
=> Use pacman architecture instead of uname in some cases. Fixes #9

Cargo.lock, Cargo.toml, src/srcinfo.rs, src/wrapped.rs
This removes quite a couple of lines from rua while fixing a bug and altering the behaviour a little bit (see the commit messages)
This is also my own crate, I feel a little weird about pushing my own stuff on others but it does seem to meet your needs.
=> Use the srcinfo crate for srcinfo parsing

src/main.rs
In case of error, exit with a nicer message
=> check bwrap availability

Cargo.lock, Cargo.toml, src/main.rs, src/print_package_table.rs
With this PR `rua search test` works.
This is also the first time I've tested search and i'm not a fan of the output format. But to keep this PR focused all it does is switch the branch and nothing more.
=> Use my branch of raur

src/pacman.rs, src/wrapped.rs
This was fixed in c76710a8 then later unfixed in fc548e3f.
=> Use correct arch

README.md, src/action_install.rs, src/main.rs, src/pacman.rs, src/wrapped.rs
This is a preparation to fix issue #1, similar to the already existing PR #37.
=> split "installation" logic from "bubblewrap" logic

res/shellcheck-wrapper, src/action_install.rs, src/main.rs, src/pacman.rs, src/reviewing.rs, src/rua_files.rs, src/tar_check.rs, src/wrapped.rs
fixes GH-21
@Morganamilo same as with the other MR, please write whether you'de be willing to review this one or not.
=> add support for split packages

Cargo.lock, Cargo.toml, README.md, release.sh, res/shellcheck-wrapper, res/wrap.sh, src/action_builddir.rs, src/action_install.rs, src/action_upgrade.rs, src/cli_args.rs, src/git_utils.rs, src/main.rs, src/pacman.rs, src/reviewing.rs, src/rua_environment.rs, src/srcinfo_to_pkgbuild.rs, src/tar_check.rs, src/terminal_util.rs, src/wrapped.rs
fixes GH-34
@Morganamilo same as with the other MRs, please write whether you'de be willing to review this one or not.
=> implement upgrade action

src/action_install.rs, src/action_upgrade.rs, src/aur_rpc_utils.rs
=> grouped "upgrade" information fetching

README.md, src/action_builddir.rs, src/action_install.rs, src/action_upgrade.rs, src/cli_args.rs, src/main.rs, src/rua_environment.rs, src/wrapped.rs
use srcinfo information to improve "builddir" action
also, add support for --force key of makepkg
=> use srcinfo information to improve "builddir" action

Cargo.lock, Cargo.toml, src/action_install.rs, src/rua_files.rs
=> fix directory removal by using newest version of rm_rf crate

src/action_builddir.rs, src/action_install.rs, src/reviewing.rs, src/rua_environment.rs, src/rua_files.rs, src/wrapped.rs
As discussed previously [here](https://github.com/vn971/rua/pull/110#discussion_r397505157).
=> Rename RuaDirs struct to RuaPaths

src/action_builddir.rs, src/action_install.rs, src/action_upgrade.rs, src/main.rs, src/reviewing.rs, src/rua_environment.rs, src/rua_paths.rs, src/wrapped.rs
=> do not instantiate RuaPaths for passive commands

src/action_install.rs
A vastly simpler take on #115.
=> Fix symlinks making jailed PKGBUILDs read-only (take B)

src/git_utils.rs
Fixes https://github.com/vn971/rua/issues/132
=> Make git behavior predictable

README.md
See https://github.com/vn971/rua/issues/170
=> Remove git feature mention from readme

src/action_install.rs, src/rua_paths.rs
Fixes https://github.com/vn971/rua/issues/145
=> Remove "dirty" build directory after successful install

src/tar_check.rs
Fixes #135, first time making a pr so let me know if anything needs changing!
=> Add new files package analysis option
